### ISSUE TITLE
Would you support a F-Droid store inclusion?

### ISSUE THREAD

**Issue by revuwa** [darshanparajuli/LogcatReader#1]
Thanks for your awesome app, and especially for publishing the source code.

I think it would be great to see your app in the [F-Droid](https://f-droid.org/) store and made an request for packaging, already [here](https://gitlab.com/fdroid/rfp/issues/459).
Would this be OK for you and would you support the inclusion?

**Comment by darshanparajuli** [comment]
Sounds good, thanks!

**Comment by IzzySoft** [comment]
@revuwa there seem to be some gradle issues. Could you [please chime in here](https://gitlab.com/fdroid/rfp/issues/459)? Thanks in advance!

**Comment by darshanparajuli** [comment]
@IzzySoft  Is it related to `gradle/wrapper/gradle.properties is missing distributionSha256Sum, unverified gradle download!`?

**Comment by IzzySoft** [comment]
@darshanparajuli Exactly that. But I'm not a dev, so better ask "behind the link" I gave :wink:

**Comment by darshanparajuli** [comment]
@IzzySoft Ahh.. I have never dealt with F-Droid, so I was asking to make sure.

**Comment by IzzySoft** [comment]
No harm done. I was just pointing as I wasn't sure whether you might have missed it. So clarification is best done "over there" where the maintainers are, as they might have good pointers as well.

**Comment by Rudloff** [comment]
The warning means that you should add this to `gradle-wrapper.properties`:
```diff
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index af91ab6..18dee10 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -4,3 +4,4 @@ distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
 distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
+distributionSha256Sum=7a2c66d1a78f811d5f37d14630ad21cec5e77a2a4dc61e787e2257a6341016ce
```

This way, the build system can verify that the downloaded gradle binary is correct.

**Comment by darshanparajuli** [comment]
@Rudloff thanks! 
e32fa68acff78d6f8df9dbf6d10ad98d31a611fd

**Comment by mueller-ma** [comment]
@darshanparajuli You could add some metadata (description, images) to this repo, so F-Droid can show them.
Example: https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US

**Comment by IzzySoft** [comment]
As F-Droid inclusion seems to take a while: if you could add an `.apk` to each release (starting with the current), @darshanparajuli, I could meanwhile make your app available via [my repo](https://apt.izzysoft.de/fdroid/repo).
