### ISSUE TITLE
Crash when switching buffers

### ISSUE THREAD

**Issue by rmenessec** [darshanparajuli/LogcatReader#2]
Crashed when attempting to deselect the "main" log buffer.

Android 7.1.2, LineageOS, latest nightly.

**Comment by darshanparajuli** [comment]
Could you tell me the following?

1. buffers shown
2. buffers selected before you tried deselecting "main"

Thanks!

**Comment by rmenessec** [comment]
@darshanparajuli, I was trying to remove "main" from the three default buffers selected, is all.

**Comment by darshanparajuli** [comment]
@rmenessec Does it happen every time?

**Comment by darshanparajuli** [comment]
So I installed LineageOS 14.1 on my spare phone (HTC One m7), and I was able to deselect 'main' buffer without any problems on the latest version of the app. If this is a reproducible issue on your device, could you please post the logcat? Thanks!

**Comment by rmenessec** [comment]
It happened three times, so I gave up and uninstalled the app.

**Comment by rmenessec** [comment]
Seems silly to ask this, but can you recommend another logcat tool in case LogcatReader crashes again before I can get the logcat data? Can you recommend a tool which deletes sensitive data (IP addresses, host names, user names, passwords, network adapter addresses, serial numbers...) from the captured data?

NOTE: LogcatReader is the only app of about

Also, which buffers do you want captured?

**Comment by darshanparajuli** [comment]
I was merely asking you to run `adb logcat` from the command line, copy paste it onto a text file, and post the relevant logs by searching for `com.dp` (it shouldn't include sensitive data), if at all possible.
I know it sounds a bit too much to ask, but it's the quickest way to find out what's causing the crash on your particular device.

**Comment by rmenessec** [comment]
@darshanparajuli, actually, I've done that before. If you decide you need the data after all, let me know. And thanks. 😉

**Comment by darshanparajuli** [comment]
@rmenessec Sounds good, thanks!
