### ISSUE TITLE
Search: Retain search value onResume

### ISSUE THREAD

**Issue by KreAch3R** [darshanparajuli/LogcatReader#23]
Hey, thanks for a great app!

I've noticed the below behavior:
1. Open the app, search for something:

<img src="https://user-images.githubusercontent.com/2224376/45598009-706e7c00-b9dd-11e8-8862-a69e138b999d.jpg" width="300">

2. Use the Recents button to go to another app or the Home button to go to the launcher
3. Use the Recents button to turn back into the app
4. The app will retain the search view and the search value but the results will be different:
<img src="https://user-images.githubusercontent.com/2224376/45598010-706e7c00-b9dd-11e8-81d2-94f547f7fc02.jpg" width="300">

5. Pressing "Enter" into the search text box won't refresh the results. You need to delete everything, then re-type, then press "Enter" again to get the same results as before onResume.

**Comment by darshanparajuli** [comment]
It's been fixed and will be on the next update. Thanks!

2453a2b418f1c0d0dd11d40dbb4cbfa0c26524ba
