### ISSUE TITLE
please put app/uid/.../message on the same line in export, to make filtering easier

### ISSUE THREAD

**Issue by TjrGithub** [darshanparajuli/LogcatReader#32]
A lot of people simply grep the logcat file for the affected app or uid when they want to report a bug. Could you please make LogcatReader put the app and the actual message on the same line in the exported file?

Current format:
[04-07 17:26:28.915 14142:14167 I/Adreno]
QUALCOMM build                   : 2371bd1, I8ebe47d372
Build Date                       : 03/12/18

Suggested format:
[04-07 17:26:28.915 14142:14167 I/Adreno] QUALCOMM build                   : 2371bd1, I8ebe47d372
[04-07 17:26:28.915 14142:14167 I/Adreno] Build Date                       : 03/12/18

**Comment by darshanparajuli** [comment]
Thank you for the suggestion! I have added an option to export in single-line mode. The main caveat with single-line mode is that the app is unable to parse that text file. Thus, you won't be able to view the logs if you choose to open that file with this app (unlike the default mode). 

63208c8b8a92ad9bc2f61f4cfc4909d1fa8a9ead

**Comment by TjrGithub** [comment]
Thanks. I'll try it out as soon as it's on FDroid.
