### ISSUE TITLE
Stop logcat reader service

### ISSUE THREAD

**Issue by Alexmark1** [darshanparajuli/LogcatReader#40]
Maybe this is a bug or maybe only a stupid question: after using logcat reader I retain a notification saying "logcat reader service". Does this mean the service keeps running? Is there a way to stop it other than force stop the app? A menu option like "Exit" would be good. After viewing logs I often do not use the app for weeks and it feels odd to leave the service running when it's not needed (like for battery life etc).

**Comment by Alexmark1** [comment]
ok, tapping back twice works, but a menu item would be good for those who do not read the FAQ first. ;-)

**Comment by V3D3NO23** [comment]
La verdad nose deloque hablas yo nunca e tenido esa app ??Creo que teas
ekibocado de correo ??🤔🤔🤔💩

**Comment by darshanparajuli** [comment]
You can tap "Exit" on the notification to make it go away. Let me know if that doesn't work. Thanks!

**Comment by Alexmark1** [comment]
You are right, there is an Exit button, it just wasn't visible initially on my device. I had to pull down the thin separator at the bottom of the notification to make it visible. Maybe that is a device specific problem; maybe one less line break in the notification would make it fool proof.
