### ISSUE TITLE
[suggestion] could you merge a shuzuku support

### ISSUE THREAD

**Issue by NewBugger** [darshanparajuli/LogcatReader#44]
`shizuku` is a tool for using some operations in only ADB permission, details: https://shizuku.rikka.app/

if the user has uses shizuku, then he could use Logcatapp without adb command again

then i made the support for this tool (this commit might have api level requirement, might not. worked as expected on AOSP Android 10): https://github.com/NewBugger/LogcatReader/commit/95ce84b41cc424b97935a7a2140ba14817733449

i did not create pull request because i thought my code is not the fimiliar style as yours.

thanks all yours credits.

**Comment by jabberwooky** [comment]
Thanks for your support , but I've got only Android 7 ( nougat )
Hope on your support in future .
Thanks you also for fast answers .
See you .
M.G.

Destroyer of the black Tower

Suzukaze Aoki <notifications@github.com> schrieb am Mi., 22. Juli 2020,
05:20:
