### ISSUE TITLE
Crashes on Android 11

### ISSUE THREAD

**Issue by PeterNjeim** [darshanparajuli/LogcatReader#49]
I used to use this app but when I updated to an Android 11 custom ROM the app now crashes immediately upon opening. I checked the reviews and it seems there is at least one other person who has mentioned Android 11 being the cause of this crash.

Android crash log url: [https://del.dog/ecrockebuc]()

**Comment by bengalih** [comment]
Can confirm this issue as well on Android 11 Pixel 3 XL (crosshatch).  January update, clean build.

**Comment by Gamemulatorer** [comment]
Not crashing on my Redmi Note 9 a11 miui 12.5.1

**Comment by PeterNjeim** [comment]
This has been fixed a while ago lol. Forgot that I even made this issue
