### ISSUE TITLE
Logcat standard output format different from Logcat Reader output format

### ISSUE THREAD

**Issue by antoniu200** [darshanparajuli/LogcatReader#67]
Hi!

I have just noticed that your app is outputting logs in a slightly different format that the one specified on Android Developer website: https://developer.android.com/studio/debug/am-logcat#format

There it is described as
`date time PID-TID/package priority/tag: message`

Outputted from your app, it seems like it is rather
`[date time PID:TID priority/tag]`
`message`

Is there something I am missing in the official documentation?

**Comment by darshanparajuli** [comment]
I believe this was a choice that was made initially (can't remember the reason exactly, maybe to be able to load the saved/exported logs back into the app). Logs can be exported in one of the two formats below:
```
[date time PID:TID priority/tag]
message
```
or
```
[date time PID:TID priority/tag] message
```

At the time I didn't think it mattered enough to keep the same formatting. Curious if it does though.
