### ISSUE TITLE
Android 13 update and LogcatReader behaviour

### ISSUE THREAD

**Issue by DavidH-Tech** [darshanparajuli/LogcatReader#70]
A popup will show up by Android 13 to prompt user access to "usage logs", have you noticed it @darshanparajuli 

There is unfortunately no way to bypass it on Android 13, we may need some change to the instructions on granting permissions manually
![Screenshot_2022-12-01-18-48-44-23_c31b32364ce19ca8fcd150a417ecce58](https://user-images.githubusercontent.com/106898439/205203990-071c5558-71d0-4d2d-b962-384e479485de.jpg)

**Comment by darshanparajuli** [comment]
It seems to work as expected if you simply tap "Allow one-time access", which is a fine behavior IMO. Thoughts?

**Comment by DavidH-Tech** [comment]
OK we can close this now then
