### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [darshanparajuli/LogcatReader#8]
Hi, I want to design a new logo for the project completely free...

**Comment by Arslanshn** [comment]
https://drive.google.com/file/d/1ywOi2m9xqPDiVa3VrkFTvXmNa20D0jYE/view?usp=drivesdk

**Comment by darshanparajuli** [comment]
Alright. One more question, are you going to follow material design guidelines as you design the logo?

**Comment by Arslanshn** [comment]
Yes of course. This is only sketch

**Comment by darshanparajuli** [comment]
I was just making sure xD
Please keep me posted with your progress in the design. Thanks!

**Comment by Arslanshn** [comment]
Hello You can look at the logo:-)

**Comment by Arslanshn** [comment]
You can look at the logo:)

**Comment by Arslanshn** [comment]
https://drive.google.com/folderview?id=12h6k8U0LZ51rK7-7uFQ3hR-pA7A3QqdA

**Comment by darshanparajuli** [comment]
Looks great! Could you post more samples using the app's color scheme (teal)?

**Comment by darshanparajuli** [comment]
Awesome, thanks!

**Comment by Arslanshn** [comment]
hi I ended the logo, I hope it is as you like :)

**Comment by darshanparajuli** [comment]
I really like the L2 design (teal one); it looks fantastic. Nice job dude! Would you like to make a PR or should I add it myself (crediting you, of course)?

**Comment by Arslanshn** [comment]
Hey, you can add. When will you add it?:-)

**Comment by darshanparajuli** [comment]
Hopefully this weekend!

**Comment by Arslanshn** [comment]
Good day to rejoice if you let me know when you load it.

**Comment by darshanparajuli** [comment]
Hey @Arslanshn, could you export L2 design of the icon to size 512x512? Thanks!

**Comment by Arslanshn** [comment]
I did it the way you like. I wish you a good day:-)

**Comment by darshanparajuli** [comment]
Thanks! I updated the launcher icons to the new logo. 469adadf9b9d9abc350dd98a9f6c3cb3e56e0408
Would you like to help with splash screen as well?

**Comment by Arslanshn** [comment]
I did 2 jobs for the startup screen and uploaded. I guess it's not something I understand.Hi, logo loaded? I can not see..

**Comment by darshanparajuli** [comment]
Thanks! I was only asking since you seem to have an easy way to render logos to various forms and sizes.

The splash screens look good; just need the background to be the primary color of the app (teal, `#009688`) with white foreground (icon in the middle), and in following sizes:
```
Portrait: 200x320px. Landscape: 320x200px.
Portrait: 320x480px. Landscape: 480x320px.
Portrait: 480x800px. Landscape: 800x480px.
Portrait: 720px1280px. Landscape: 1280x720px.
Portrait: 960px1600px. Landscape: 1600x960px.
Portrait: 1280px1920px. Landscape: 1920x1280px
```
Thank you so much!

The new logo has been added in the branch `new-logo` at the moment. Once I have the splash screens, I'll merge it with `master` and publish an update on the play store.

**Comment by Arslanshn** [comment]
Hello, I hope I did that and I want to install the business benefits...

**Comment by Arslanshn** [comment]
I did a study. I hope it works for you.I wanted to write. I ama so sorry..

**Comment by Arslanshn** [comment]
Hi Darshanparajuli When do you plan to use the Logo..

**Comment by darshanparajuli** [comment]
Sorry, I have been super busy with school work lately. I'll update the logo by the end of this week.

**Comment by darshanparajuli** [comment]
Hey @Arslanshn, as I was adding the splash screen images, I noticed their sizes were 1 pixel more than what they should be. For example, 481x801 instead of 480x800. Could you please fix that?

**Comment by Arslanshn** [comment]
Hi, I made the correction:)

**Comment by darshanparajuli** [comment]
Merged the new icons and splash screens (54b863ca988c0038afeefe513ffe2682c9d20ae9, 6655a0d9aa0a66539b188dd86cd6098457449101), thank you so much!

**Comment by Arslanshn** [comment]
I thank you. I think the Playstore and F-Droid also have the old logo?

**Comment by darshanparajuli** [comment]
Yeah, I'll publish an update with the new logo and other fixes/features soon.

**Comment by Arslanshn** [comment]
README.md 
Bölümüne bir logo ekleyebilirmisin?

**Comment by Arslanshn** [comment]
Hello Darshan

**Comment by darshanparajuli** [comment]
Hey @Arslanshn, I have added the logo to the README.

**Comment by Arslanshn** [comment]
Thank you Darshan 😀

**Comment by darshanparajuli** [comment]
No problem!
